"""language

Revision ID: e2a70e669a20
Revises: 251c3fd09765
Create Date: 2021-12-04 02:02:42.551741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a70e669a20'
down_revision = '251c3fd09765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('language', sa.String(), nullable=True))
    op.add_column('snippets', sa.Column('theme', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('snippets', 'theme')
    op.drop_column('snippets', 'language')
    # ### end Alembic commands ###
